apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qa-mock
  name: qa-mock
  namespace: ph-stg
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: qa-mock
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qa-mock
    spec:
      containers:
      - args:
        - mock.py
        command:
        - python
        image: registry-intl.ap-southeast-1.aliyuncs.com/oriente-bigdata/qa-mock:dev_210526_07
        imagePullPolicy: Always
        name: qa-mock
        resources:
          limits:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
